platform:
  - x86

install:
  # Installing Rust distribution
  - choco install --yes --x86 --version=1.8 rust
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust stable GNU 1.8\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
