version: '0.1.0-RC0-b{build}'

platform:
  - x86

install:
  # Installing Rust distribution
  - choco install --yes --x86 --version=1.11 rust
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust stable GNU 1.11\bin
  - rustc -V
  - cargo -V
  # Installing NSIS
  - choco install --yes nsis
  - set PATH="C:\Program Files (x86)\NSIS";%PATH%
  - curl -fsS -o C:\Windows\Temp\nsis-xml.zip http://nsis.sourceforge.net/mediawiki/images/5/55/Xml.zip
  - md C:\Windows\Temp\nsis-xml
  - 7z x -oC:\Windows\Temp\nsis-xml C:\Windows\Temp\nsis-xml.zip
  - copy C:\Windows\Temp\nsis-xml\Plugin\xml.dll C:\Program Files (x86)\NSIS\Plugins\x86-ansi

test_script:
  - cargo test --verbose

build_script:
  - cargo build --verbose --release
  - makensis /DFLIGHTVARS_VERSION=%APPVEYOR_BUILD_VERSION% installer\FlightVars.nsh

artifacts:
  - path: installer/*.exe
deploy:
  description: 'FlightVars plugin for FSX/P3D'
  provider: GitHub
  auth_token:
    secure: 4QP9Hc3xgTn+8pJQTfK7Ooq4quBsecJX84qgBqnta3EnbeNTiEDCrDCJ2KNHn1vZ
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
