platform:
  - x86

install:
  # Installing Rust distribution
  - choco install --yes --x86 --version=1.8 rust
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust stable GNU 1.8\bin
  - rustc -V
  - cargo -V
  # Installing InnoSetup
  - choco install --yes InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - cargo build --verbose --release
  - iscc installer/FlightVars.iss /DPWD=%CD%

test_script:
  - cargo test --verbose
