[package]
name = "flightvars"
version = "0.1.0"
authors = ["Alvaro Polo <apoloval@gmail.com>"]

[dependencies]
byteorder = "0.4.2"
hex = "0.1.0"
libc = "*"
log = "*"
log4rs = "*"

[lib]
crate-type = ["dylib"]
